### ISSUE TITLE
Create transaction list (plus history per session)

### ISSUE THREAD

**Issue by wirednkod** [delegit-xyz/dashboard#72] opened 2024-08-30 21:18 UTC
We need to have a popup (called Toaster / sonner) for the transactions that happen in the background.
It would be nice to have per session (while browser is on), the "historical tranasctions" that one did - so that one can copy/paste the tx Id, or see the result of the transaction, instead of realying to check on the wallet.

**Comment by Tbaut** [comment] 2024-09-01 12:47
The problem here is to know what you did in the past right?
I don't want to transform Delegit into a wallet though. Previous Txs is something where an indexer is absolutely needed, however I'm not sure this is really needed. If we concentrate on delegation for now, all you need to know is whether you're delegating. The locks from votes are displayed, bc we need this info and figured it's good for users to know, but it's actually not 100% related.
What actions do we have?
- clean the lock -> locks should be 0
- delegate -> see the delegation
- undelegate -> the no delegation
- change delegate -> see the new delegate

There's no action for which the consequence shouldn't be directly visible to users, and then having a list of past Txs doesn't appear as needed to me.

**Comment by wirednkod** [comment] 2024-09-01 15:33
Understood. The idea behind initiating this, was, when i make a delegation, i want to know the result. And if it failed, why it failed. By "history" i mean only the actions that a user did in the session active , not past logins, meaning nothing will be saved locally or not

**Comment by Tbaut** [comment] 2024-09-01 17:32
ok, so this: https://github.com/delegit-xyz/dashboard/issues/87
And make sure that when there's an error, it's not removed automatically maybe

**Comment by Tbaut** [comment] 2024-09-11 10:04
closing as duplicate of #87

**Closed by Tbaut** 2024-09-11 10:04 UTC
Labels: Priority: 🟡 P2, Type: 🫶 Enhancement
